### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by r-dh** [xrlabdevelopment/Sophia#8]
### Unit Tests - Sophia.Algo
- [x] Clamp

### Unit Tests - Sophia.Events
- [x] Event
- [x] EventDispatch
- [x] IEvent
- [x] IEventHandler
- [x] IEventSender

### Unit Tests - Sophia.IO
- [ ] FileSystemWatcher

### Unit Tests - Sophia.Patterns
- [x] ICommand
- [x] ICommandReceiver
- [x] FiniteStateMachine
- [x] FSMEvent
- [x] FSMState
- [x] FSMTransition
- [x] IStateMachine
- [x] Observer
- [x] ObserverEvent
- [x] Subject
- [x] SubjectEvent
- [x] Singleton

### Unit Tests - Sophia
- [x] TimerManager
- [x] CountDown Timer

**Comment by Dyronix** [comment]
Finished all tests
