### ISSUE TITLE
Refactor serialization

### ISSUE THREAD

**Issue by r-dh** [xrlabdevelopment/Sophia#9]
### Refactor - Serialization
[XmlSerializer Class Reference](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer?view=netcore-3.1)
- [ ] Design a generic framework to serialize data in XML
- [ ] Investigate the current serialization framework inside Sophia
- [ ] Unit test this new framework
- [ ] Apply serialization to the recorder framework
    - [ ] Action
    - [ ] IAction
    - [ ] IActionFactory
    - [ ] Recorder
    - [ ] Playback

- [ ] Apply serialization to the settings framework
    - [ ] ISetting
    - [ ] ISettings
    - [ ] Setting
    - [ ] Settings
    - [ ] SettingsManager

**Comment by Dyronix** [comment]
Serialization has been removed.
